import type { Option } from '../pickers/Select'

const CC_NAMES = [
  'Bank Select',
  'Modulation Wheel',
  'Breath Controller',
  '',
  'Foot Control',
  'Portamento Time',
  'Data Entry Slider',
  'Volume',
  'Balance',
  '',
  'Pan',
  'Expression',
  'Effect Control 1',
  'Effect Control 2',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Controller 0',
  'Controller 1',
  'Controller 2',
  'Controller 3',
  'Controller 4',
  'Controller 5',
  'Controller 6',
  'Controller 7',
  'Controller 8',
  'Controller 9',
  'Controller 10',
  'Controller 11',
  'Controller 12',
  'Controller 13',
  'Controller 14',
  'Controller 15',
  'Controller 16',
  'Controller 17',
  'Controller 18',
  'Controller 19',
  'Controller 20',
  'Controller 21',
  'Controller 22',
  'Controller 23',
  'Controller 24',
  'Controller 25',
  'Controller 26',
  'Controller 27',
  'Controller 28',
  'Controller 29',
  'Controller 30',
  'Controller 31',
  'Sustain',
  'Portamento',
  'Sostenuto',
  'Soft Pedal',
  'Legato Pedal',
  'Sustain 2',
  'Sound Variation',
  'Resonance/Timbre',
  'Sound Release Time',
  'Sound Attack Time',
  'Frequency Cutoff',
  'Sound Control 6',
  'Sound Control 7',
  'Sound Control 8',
  'Sound Control 9',
  'Sound Control 10',
  'Decay or General 1',
  'Hi-Pass or General 2',
  'General 3',
  'General 4',
  'Portamento Amount',
  '',
  '',
  '',
  '',
  '',
  '',
  'Reverb Level',
  'Tremolo Depth',
  'Chorus Level',
  'Detune',
  'Phaser Depth',
  'Data Entry +1',
  'Data Entry -1',
  'Non-registered LSB',
  'Non-registered MSB',
  'Registered msb',
  'Registered lsb',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Shift 1',
  'Shift 2',
  'Shift 3',
  'Shift 4',
  'Shift 5',
  'Shift 6',
  '',
  '',
  '',
  '',
  'All Sound Off',
  'All Controllers Off',
  'Local Mode',
  'All Notes Off',
  'Omni Mode Off',
  'Omni Mode On',
  'Mono Mode On',
  'Poly Mode',
].map(
  (label, value): Option<number> => ({
    label: String(label).length ? `${value} - ${label}` : String(value),
    value,
  }),
)

export default CC_NAMES
